### PR TITLE
Fix union-type handling in PublicPropertyFetchCollector

### LINKED ISSUE #119: union type support
properties are reported unused even though they are used via union type:
```php
<?php

class A {
    public float $amount;
}

class B {
    public float $amount;
}


/** @param A|B $aOrB */
function doFoo($aOrB): void {
    echo $aOrB->amount;
}

function doFooBar(A|B $aOrB): void {
    echo $aOrB->amount;
}

```

reports

```
 ------ -------------------------------------------------------------------------------------------------------- 
  Line   test.php
 ------ --------------------------------------------------------------------------------------------------------
  3      Public property "A::$amount" is never used
         💡 Either reduce visibility or annotate it or its class with @api
  7      Public property "B::$amount" is never used
         💡 Either reduce visibility or annotate it or its class with @api

```

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/TomasVotruba/unused-public/issues/119

### CODE REVIEW

File: src/Collectors/PublicPropertyFetchCollector.php [hunk 1]
```diff
@@ -53,19 +53,23 @@ public function processNode(Node $node, Scope $scope): ?array
             return null;
         }
 
-        $propertyFetcherType = $scope->getType($node->var);
-        if (! $propertyFetcherType instanceof TypeWithClassName) {
```
Comment (staabm) [inline src/Collectors/PublicPropertyFetchCollector.php:57]: this kind of bugs are the reason why these instanceof checks are deprecated:

https://phpstan.org/blog/why-is-instanceof-type-wrong-and-getting-deprecated

File: tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php [hunk 2]
```diff
@@ -109,6 +109,10 @@ public static function provideData(): Iterator
             ],
             [],
         ];
+
+        yield [[__DIR__ . '/Fixture/UsedInUnionA.php', __DIR__ . '/Fixture/UsedInUnionB.php', __DIR__ . '/Source/UsedInUnion.php'], []];
+        yield [[__DIR__ . '/Fixture/UsedInUnionA.php', __DIR__ . '/Fixture/UsedInUnionB.php', __DIR__ . '/Source/UsedInUnionPhpdoc.php'], []];
```
Comment (staabm) [inline tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: btw: IMO as someone used to the 1-file test-cases from the phpstan-src repo, this separation of classes over several files (fixture + source) makes creating unit tests pretty hard and unnecessary complex

File: src/Collectors/PublicPropertyFetchCollector.php (hunk 1 above)
Comment (TomasVotruba) [reply src/Collectors/PublicPropertyFetchCollector.php:57]: IDE support is the reason 🙏

File: tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php (hunk 2 above)
Comment (TomasVotruba) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: What do you suggest?

Comment (staabm) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: I would put all classes for a single test-case into a single file (with a unique namespace) and use composer class-map autoloading for tests instead of psr-4.

see https://github.com/phpstan/phpstan-src/blob/89636d6983c73687a9c6d50deac0b01158291f59/composer.json#L133-L136

but not in this PR of course.. it fixes a problem unrelated to this file-system design thing ;)

Comment (TomasVotruba) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: I see. For the `/Source` it made mess as people used same-named classes: )

**Comment by TomasVotruba** [comment]
Looks good, thanks 👍

File: tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php (hunk 2 above)
Comment (staabm) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: for the PR we have here, that would mean the test-case file would look like:

```
namespace Bug119;

class UsedInUnionA {
    public float $amount;
}

class UsedInUnionB {
    public float $amount;
}

function doFooBar(UsedInUnionA|UsedInUnionB $aOrB): void {
    echo $aOrB->amount;
}

```

- no separation in fixture/source
- no complicated file path mapping in the *RuleTest.php
- easier handling, because a test-case can be deleted with a single file (no dependencies outside the test-file)

Comment (staabm) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: > same-named classes: )

therefore a dedicated namespace for each test.

Comment (staabm) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: in phpstan-src there is a CI check to make sure class-names are unique - shipmonk/name-collision-detector

**Comment by staabm** [comment]
> Looks good, thanks

thanks. I prepare another PR with the same fix for static properties

File: tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php (hunk 2 above)
Comment (TomasVotruba) [reply tests/Rules/UnusedPublicPropertyRule/UnusedPublicPropertyRuleTest.php:114]: > therefore a dedicated namespace for each test.

That's the place people failed :) we had dozens such cases in Rector, often easy to miss in IDE.
